### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by liketechnik** [sakaki-/bcmrpi3-kernel-bis#11]
First: Thank you for your amazing work bringing gentoo (or a 64bit OS in general) on the raspberry pi 3/4.
Now to my problem/question: The docker daemon crashes on my pi because it can't setup iptables. Additionally it warns about the modules 'bridge' and 'ip_tables' not being available. I'm pretty sure there are even more kernel configs that need to be changed to have docker running, but I'm not really sure a) what needed to be changed (but I think I could look this up in the docker ebuild) b) and where I could change these things.

**Comment by sakaki-** [comment]
Hi @liketechnik,

This is curious, as a number of people have used docker successfully under the [`gentoo-on-rpi-64bit`](https://github.com/sakaki-/gentoo-on-rpi-64bit) image (which in turn uses this kernel on the RPi3B/B+, and its sister [`bcm2711-kernel-bis`](https://github.com/sakaki-/bcm2711-kernel-bis) for the RPi4B). See e.g. [this post](https://www.raspberrypi.org/forums/viewtopic.php?p=1577365#p1577365) _ff_ (docker / portainer / pihole):

![Screenshot of Docker / Portainer / Pihole on RPi4 Gentoo](https://raw.githubusercontent.com/sakaki-/resources/master/raspberrypi/pi4/docker-portainer-pihole.jpg)

Not sure what userland O/S you are using, but if gentoo, then note that due to e.g. the seccomp filtering this uses for docker by default, you may need to use **privileged mode** for docker (as I did in the above).

hth, sakaki

**Comment by liketechnik** [comment]
At some point I must have lost track of this 🤔 

Since it works/worked for everybody else, I'll go ahead and close this.
